pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - label!=manual merge
      - "#approved-reviews-by>=1"
    actions:
      merge:
        strict: smart
        method: squash
