version: 2

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
