[tool.isort]
force_single_line = true
lines_after_imports = 2
force_sort_within_sections = true
known_first_party = "riot"
default_section = "THIRDPARTY"

[tool.black]
exclude = '''
  (
    /(
      \.venv.*
      | \.riot
    )/
  )
'''
