name: Test
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pytest black
    - name: Check format
      run: |
        black --check .
    - name: Run tests
      run: |
        pytest tests/
